name: 4 Legged Mountain
favicon: null
layout_spectrum: 0.236
typography_spectrum: 0.88887
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cac5cc'
    - '#797da0'
    - '#f7fbed'
    - '#232b40'
    - '#d8676b'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
